// todolist-vuex/src/components/Item.vue
<template>
  <li>
    <label>
      <input type="checkbox" :checked="todo.done" @change="handleCkeck(todo.id, $event)" />
      <span>{{todo.name}}</span>
    </label>
    <button class="btn btn-danger" @click="handleDelete(todo.id)">删除</button>
  </li>
</template>

<script>
import { UPDATE_TODO, DELETE_TODO } from '../store/mutation-types';

export default {
  name: 'Item',
  props: ['todo'],
  methods: {
    // 勾选、取消勾选某一个todo的回调
    handleCkeck(id, $event) {
      const done = $event.target.checked
      this.$store.commit(UPDATE_TODO, {id, done})
    },
    // 删除一个todo的回调
    handleDelete(id) {
      this.$store.commit(DELETE_TODO, id)
    }
  }
}
</script>

<style>
li {
  list-style: none;
  height: 36px;
  line-height: 36px;
  padding: 0 5px;
  border-bottom: 1px solid #ddd;
}

li:hover {
  background-color: #ddd;
}

li label {
  float: left;
  cursor: pointer;
}

li label li input {
  vertical-align: middle;
  margin-right: 6px;
  position: relative;
  top: -1px;
}

li button {
  display: none !important;
  float: right;
  display: none;
  margin-top: 3px;
}

li:hover button {
  display: block !important;
}

li:before {
  content: initial;
}

li:last-child {
  border-bottom: none;
}
</style>

// todolist-redux/src/components/Item/index.jsx
import store from '../../redux/store'
import { updateTodo, deleteTodo } from '../../redux/actions'
import './index.css'

const Item = (props) => {
  const { id, name, done } = props

  // 勾选、取消勾选某一个todo的回调
  const handleCkeck = (id) => {
    return (event) => {
      const done = event.target.checked
      store.dispatch(updateTodo({id, done}))
    }
  }

  // 删除一个todo的回调
  const handleDelete = (id) => {
    store.dispatch(deleteTodo({id}))
  }

  return (
    <li>
      <label>
        <input type="checkbox" checked={done} onChange={handleCkeck(id)} />
        <span>{name}</span>
      </label>
      <button className="btn btn-danger" onClick={() => handleDelete(id)}>删除</button>
    </li>
  )
}

export default Item
