// todolist-vue3-pinia/src/components/Footer.vue
<template>
  <div class="todo-footer">
    <label>
      <input type="checkbox" :checked="todo.isChecked" @change="handleCheckAll" />
    </label>
    <span>
      <span>已完成{{ todo.doneCount }}</span> / 全部{{ todo.total }}
    </span>
    <button class="btn btn-danger" @click="todo.clearAllDone">
      清除已完成任务
    </button>
  </div>
</template>

<script setup>
import { useTodoState } from '../stores/todo'

const todo = useTodoState()

//全选checkbox的回调
const handleCheckAll = ($event) => {
  todo.checkAllTodo($event.target.checked)
}
</script>

<style lang="less">
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;

  label {
    display: inline-block;
    margin-right: 20px;
    cursor: pointer;

    input {
      position: relative;
      top: -1px;
      vertical-align: middle;
      margin-right: 5px;
    }
  }

  button {
    float: right;
    margin-top: 5px;
  }
}
</style>

// todolist-react/src/components/Footer/index.jsx
import './index.css';

const Footer = (props) => {
  const { todos, checkAllTodo, clearAllDone } = props
  const total = todos.length
  const doneCount = todos.reduce((pre, current) => {
    return pre + (current.done ? 1 : 0)
  }, 0)

  //全选checkbox的回调
  const handleCheackAll = (event) => {
    checkAllTodo(event.target.checked)
  }

  // 清除所有已完成
  const handleCLearAllDone = () => {
    clearAllDone()
  }

  return (
    <div className="todo-footer">
      <label>
        <input type="checkbox" checked={doneCount === total && total !== 0} onChange={handleCheackAll} />
      </label>
      <span>
					<span>已完成{doneCount}</span> / 全部{total}
				</span>
				<button className="btn btn-danger" onClick={handleCLearAllDone}>清除已完成任务</button>
    </div>
  )
}

export default Footer
