// todolist-vuex/src/components/List.vue
<template>
  <ul class="todo-main">
    <Item
      v-for="item in todos"
      :key="item.id"
      :todo="item"
    />
  </ul>
</template>

<script>
import Item from './Item.vue';

export default {
  name: 'List',
  components: { Item },
  computed: {
    todos() {
      return this.$store.state.todos
    }
  }
}
</script>

<style>
.todo-main {
  margin-left: 0px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: 0px;
}

.todo-empty {
  height: 40px;
  line-height: 40px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding-left: 5px;
  margin-top: 10px;
}
</style>

// todolist-react-redux(connect)/src/components/List/index.jsx
import { connect } from 'react-redux'
import Item from '../Item'
import './index.css';

const List = (props) => {
  const { todos } = props
   
  return (
    <ul className="todo-main">
      {
        todos.map(item => {
          return <Item key={item.id} {...item} />
        })
      }
    </ul>
  )
}

export default connect(
  state => ({todos: state}),
  {}
)(List)
