// todolist-vue/src/components/List.vue
<template>
  <ul class="todo-main">
    <Item
      v-for="item in todos"
      :key="item.id"
      :todo="item"
      v-on="$listeners"
    />
  </ul>
</template>

<script>
import Item from './Item.vue';

export default {
  name: 'List',
  components: { Item },
  props: ['todos']
}
</script>

<style>
.todo-main {
  margin-left: 0px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: 0px;
}

.todo-empty {
  height: 40px;
  line-height: 40px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding-left: 5px;
  margin-top: 10px;
}
</style>

// todolist-react-ts/src/components/List/index.tsx
import Item from '../Item'
import './index.css';

interface Todo {
  id: string
  name: string
  done: boolean
}

interface Props {
  todos: Array<Todo>
  updateTodo(id: string, done: boolean): void
  deleteTodo(id: string): void
}

const List = (props: Props) => {
  const { todos, updateTodo, deleteTodo } = props
    
  return (
    <ul className="todo-main">
      {
        todos.map(item => {
          return <Item key={item.id} {...item} updateTodo={updateTodo} deleteTodo={deleteTodo}  />
        })
      }
    </ul>
  )
}

export default List
